# Site wide configuration

title: The Open Learning Platform
description: "[ ˈlərniNG ] NOUN : The acquisition of knowledge or skills through experience, study, or by being taught."
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://open-learning.org

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Mikael Karon
  email: mikael@karon.se
  bio:
  avatar: mikael.karon.jpg
  twitter: mikaelkaron
  github: mikaelkaron
  linkedin: mikaelkaron
  google:
    plus: mikaelkaron
    ad-client:
    ad-slot:

disqus-shortname:

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
